platform :ios, '10.0'
source 'https://cdn.cocoapods.org/'
source 'git@github.com:applicaster/CocoaPods-Private.git'
source 'git@github.com:applicaster/CocoaPods.git'
source 'git@github.com:applicaster/PluginPresenter-iOS.git'
source 'git@github.com:applicaster/zapp-player-plugin-jw.git'

use_frameworks!

 pre_install do |installer|
   # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
   Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

def shared_pods
    pod 'JWPlayerPlugin'
    pod 'PluginPresenter'
    pod 'ZappPlugins'
    pod 'ApplicasterSDK'
    pod 'ZappAnalyticsPluginsSDK'
    pod 'ZappLoginPluginsSDK'
    pod 'ZappPushPluginsSDK'
    pod 'ZappGeneralPluginsSDK'
end

target 'DIRTVisionPlayer' do
	shared_pods
end

 target 'DIRTVisionPlayerTests' do
    inherit! :search_paths
    shared_pods
end
